esphome:
  name: esp-display
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable OTA updates
ota:

dashboard_import:
  package_import_url: github://J0SH912/waveshare_ESP32_epaper_configuration/blob/main/Main.yaml@V0

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Display Fallback Hotspot"
    password: "FALLBACK_PASSWORD"

captive_portal:

spi:
  clk_pin: 13
  mosi_pin: 14

display:
  - platform: waveshare_epaper
    cs_pin: 15
    dc_pin: 27
    busy_pin: 25
    reset_pin: 26
    model: 5.83in
    update_interval: 30s
    lambda: |-
      it.fill(COLOR_ON);
